# Generated by Django 3.2 on 2024-03-12 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoId', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('currentPrice', models.FloatField(default=0)),
                ('marketCap', models.FloatField(default=0)),
                ('allTimeHigh', models.FloatField(default=0)),
                ('allTimeLow', models.FloatField(default=0)),
                ('dateCreated', models.DateField(null=True)),
                ('image', models.CharField(max_length=256)),
                ('priceHistory', models.JSONField(null=True)),
                ('reportedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
